export interface Question {
  id: number;
  problem: string;
  quantityA: string;
  quantityB: string;
  options: string[];
  answer: string;
}

export interface Section {
  id: string;
  title: string;
  subtitle: string;
  difficulty: "Medium" | "Hard" | "Research";
  questions: Question[];
  category: string;
}

export interface Category {
  category: string;
  sections: Section[];
}

export const questionBank: Category[] = [
  {
    category: "sprint",
    sections: [
      {
        id: "1",
        title: "Sprint Section 1",
        subtitle: "Core Quantitative Challenges",
        difficulty: "Medium",
        category: "sprint",
        questions: [
          {
            id: 1,
            problem:
              "A car travels 120 km in 2 hours. Compare its average speed to a value.",
            quantityA: "Average speed",
            quantityB: "60 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If x = 4, compare x² to a value.",
            quantityA: "x²",
            quantityB: "16",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem:
              "If a rectangle has length 10 and width 4, compare its area to a value.",
            quantityA: "Area of rectangle",
            quantityB: "40",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "2",
        title: "Sprint Section 2",
        subtitle: "Advanced Quantitative Challenges",
        difficulty: "Hard",
        category: "sprint",
        questions: [
          {
            id: 1,
            problem:
              "A train travels 300 km in 5 hours. Compare its average speed to a value.",
            quantityA: "Average speed",
            quantityB: "50 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 2,
            problem: "If a = 2, b = 3, compare ab to a + b.",
            quantityA: "ab",
            quantityB: "a + b",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          // New questions for Sprint Section 2
          {
            id: 3,
            problem:
              "A cyclist travels 150 km in 6 hours. Compare the average speed to a value.",
            quantityA: "Average speed",
            quantityB: "25 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "If x = 5, compare 2x + 3 to a value.",
            quantityA: "2x + 3",
            quantityB: "13",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem:
              "A square has a side length of 6. Compare its perimeter to a value.",
            quantityA: "Perimeter of square",
            quantityB: "24",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "If p = 4, q = 3, compare p² - q² to a value.",
            quantityA: "p² - q²",
            quantityB: "7",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem:
              "A store offers a 20% discount on a $50 item. Compare the discount amount to a value.",
            quantityA: "Discount amount",
            quantityB: "$10",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem: "If m = 3, n = 2, compare m/n to n/m.",
            quantityA: "m/n",
            quantityB: "n/m",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 9,
            problem:
              "A circle has radius 5. Compare its area to a value (use π ≈ 3.14).",
            quantityA: "Area of circle",
            quantityB: "78.5",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem: "If x > 0, compare x + 1/x to 2.",
            quantityA: "x + 1/x",
            quantityB: "2",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
        ],
      },
      {
        id: "8",
        title: "Sprint Section 3",
        subtitle: "Mixed Quantitative Problems",
        difficulty: "Medium",
        category: "sprint",
        questions: [
          {
            id: 1,
            problem:
              "A worker completes a task in 8 hours. Compare hours per task to a value.",
            quantityA: "Hours per task",
            quantityB: "8",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If k = 6, compare k/2 to a value.",
            quantityA: "k/2",
            quantityB: "3",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem:
              "A triangle has base 10 and height 4. Compare its area to a value.",
            quantityA: "Area of triangle",
            quantityB: "20",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "If a = 7, compare a - 3 to a value.",
            quantityA: "a - 3",
            quantityB: "4",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem: "A cube has edge length 3. Compare its volume to a value.",
            quantityA: "Volume of cube",
            quantityB: "27",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "If x = 2, y = 5, compare x + y to y - x.",
            quantityA: "x + y",
            quantityB: "y - x",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 7,
            problem:
              "A sale offers 15% off a $200 item. Compare the sale price to a value.",
            quantityA: "Sale price",
            quantityB: "$170",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem: "If p = 1, q = 2, compare p + q to pq.",
            quantityA: "p + q",
            quantityB: "pq",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 9,
            problem:
              "A rectangle has length 8 and width 6. Compare its area to its perimeter.",
            quantityA: "Area",
            quantityB: "Perimeter",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 10,
            problem: "If 0 < x < 1, compare x to x².",
            quantityA: "x",
            quantityB: "x²",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
        ],
      },
      {
        id: "9",
        title: "Sprint Section 4",
        subtitle: "Complex Quantitative Analysis",
        difficulty: "Research",
        category: "sprint",
        questions: [
          {
            id: 1,
            problem: "If x and y are positive integers, compare x/y to y/x.",
            quantityA: "x/y",
            quantityB: "y/x",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 2,
            problem:
              "A sphere has radius 2. Compare its volume to a value (use π ≈ 3.14).",
            quantityA: "Volume of sphere",
            quantityB: "33.49",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem: "If a = 3, b = 4, compare √(a² + b²) to a value.",
            quantityA: "√(a² + b²)",
            quantityB: "5",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem:
              "A car’s speed increases by 10% each hour. After 1 hour from 50 km/h, compare to a value.",
            quantityA: "New speed",
            quantityB: "55 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem: "If x = -2, compare |x| to x².",
            quantityA: "|x|",
            quantityB: "x²",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem:
              "A coin is flipped 3 times. Compare probability of 3 heads to a value.",
            quantityA: "Probability of 3 heads",
            quantityB: "1/8",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem: "If x > y > 0, compare x/y to y/x.",
            quantityA: "x/y",
            quantityB: "y/x",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
        ],
      },
    ],
  },
  {
    category: "special",
    sections: [
      {
        id: "3",
        title: "Special Section 1",
        subtitle: "Special Quantitative Practice",
        difficulty: "Medium",
        category: "special",
        questions: [
          {
            id: 1,
            problem:
              "A boat travels 80 km in 4 hours. Compare its average speed to a value.",
            quantityA: "Average speed",
            quantityB: "20 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If z = 7, compare z - 2 to 5.",
            quantityA: "z - 2",
            quantityB: "5",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem:
              "A worker paints a wall in 5 hours. Compare hours per wall to a value.",
            quantityA: "Hours per wall",
            quantityB: "5",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "4",
        title: "Special Section 2",
        subtitle: "Special Quantitative Practice",
        difficulty: "Hard",
        category: "special",
        questions: [
          {
            id: 1,
            problem: "If y = 5, compare y² to a value.",
            quantityA: "y²",
            quantityB: "25",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If a = 10 and b = 2, compare a ÷ b to b ÷ a.",
            quantityA: "a ÷ b",
            quantityB: "b ÷ a",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 3,
            problem:
              "A circle has diameter 10. Compare its circumference to a value (use π ≈ 3.14).",
            quantityA: "Circumference",
            quantityB: "31.4",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "10",
        title: "Special Section 3",
        subtitle: "Advanced Special Challenges",
        difficulty: "Medium",
        category: "special",
        questions: [
          {
            id: 1,
            problem:
              "A plane travels 600 km in 2 hours. Compare its average speed to a value.",
            quantityA: "Average speed",
            quantityB: "300 km/h",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If m = 8, compare m/4 to a value.",
            quantityA: "m/4",
            quantityB: "2",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem:
              "A rectangle has length 12 and width 3. Compare its area to a value.",
            quantityA: "Area",
            quantityB: "36",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "If x = 3, compare 3x to x².",
            quantityA: "3x",
            quantityB: "x²",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem:
              "A store gives a 25% discount on a $80 item. Compare the discount to a value.",
            quantityA: "Discount amount",
            quantityB: "$20",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "If a = 5, b = 5, compare a² to b².",
            quantityA: "a²",
            quantityB: "b²",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem:
              "A triangle has base 6 and height 8. Compare its area to a value.",
            quantityA: "Area",
            quantityB: "24",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem: "If x > 0, compare x to 1/x.",
            quantityA: "x",
            quantityB: "1/x",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 9,
            problem:
              "A cube has edge length 4. Compare its surface area to a value.",
            quantityA: "Surface area",
            quantityB: "96",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem: "If p = 6, q = 2, compare p - q to q - p.",
            quantityA: "p - q",
            quantityB: "q - p",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 11,
            problem:
              "A sale offers 10% off a $50 item. Compare the sale price to a value.",
            quantityA: "Sale price",
            quantityB: "$45",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem: "If x = 4, y = 3, compare xy to x + y.",
            quantityA: "xy",
            quantityB: "x + y",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
        ],
      },
      {
        id: "11",
        title: "Special Section 4",
        subtitle: "Complex Special Challenges",
        difficulty: "Hard",
        category: "special",
        questions: [
          {
            id: 1,
            problem:
              "A cylinder has radius 3 and height 4. Compare its volume to a value (use π ≈ 3.14).",
            quantityA: "Volume",
            quantityB: "113.04",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "If a = 2, b = -3, compare a + b to ab.",
            quantityA: "a + b",
            quantityB: "ab",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 3,
            problem:
              "A die is rolled. Compare the probability of rolling a 6 to a value.",
            quantityA: "Probability of 6",
            quantityB: "1/6",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "If x² = 9, compare x to a value.",
            quantityA: "x",
            quantityB: "3",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 5,
            problem: "A square has diagonal 8√2. Compare its area to a value.",
            quantityA: "Area",
            quantityB: "64",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "If m = 5, n = 10, compare m/n to n/m.",
            quantityA: "m/n",
            quantityB: "n/m",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity B is greater",
          },
          {
            id: 7,
            problem:
              "A car travels at 60 km/h for 2 hours. Compare distance to a value.",
            quantityA: "Distance",
            quantityB: "120 km",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem: "If x = 0, compare x² to x.",
            quantityA: "x²",
            quantityB: "x",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 9,
            problem:
              "A rectangle has area 48 and width 6. Compare its length to a value.",
            quantityA: "Length",
            quantityB: "8",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem: "If a > b, compare a - b to b - a.",
            quantityA: "a - b",
            quantityB: "b - a",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 11,
            problem: "A circle has area 16π. Compare its radius to a value.",
            quantityA: "Radius",
            quantityB: "4",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem: "If x = y, compare x² to y².",
            quantityA: "x²",
            quantityB: "y²",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
    ],
  },
  {
    category: "puzzle",
    sections: [
      {
        id: "5",
        title: "Puzzle Section 1",
        subtitle: "Mathematical Riddles",
        difficulty: "Medium",
        category: "puzzle",
        questions: [
          {
            id: 1,
            problem: "What is the next number in the sequence 1, 2, 4, 7?",
            quantityA: "Next number",
            quantityB: "11",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem:
              "If the pattern increases by +1, +2, +3..., what comes after 7?",
            quantityA: "Next term",
            quantityB: "11",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem: "What is the next number in the sequence 3, 6, 12, 24?",
            quantityA: "Next number",
            quantityB: "48",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "6",
        title: "Puzzle Section 2",
        subtitle: "Advanced Mathematical Riddles",
        difficulty: "Research",
        category: "puzzle",
        questions: [
          {
            id: 1,
            problem: "What is the next number in the sequence 2, 4, 8, 16?",
            quantityA: "Next number",
            quantityB: "32",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem:
              "A sequence doubles each term. If current is 64, what is the next?",
            quantityA: "Next number",
            quantityB: "128",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem: "What is the next number in the sequence 1, 3, 6, 10?",
            quantityA: "Next number",
            quantityB: "15",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "12",
        title: "Puzzle Section 3",
        subtitle: "Pattern Recognition",
        difficulty: "Medium",
        category: "puzzle",
        questions: [
          {
            id: 1,
            problem: "What is the next number in the sequence 5, 10, 20, 40?",
            quantityA: "Next number",
            quantityB: "80",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "What is the next number in the sequence 2, 5, 11, 23?",
            quantityA: "Next number",
            quantityB: "44",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 3,
            problem: "What is the next number in the sequence 1, 4, 9, 16?",
            quantityA: "Next number",
            quantityB: "25",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "What is the next number in the sequence 10, 9, 7, 4?",
            quantityA: "Next number",
            quantityB: "0",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem: "What is the next number in the sequence 3, 9, 27, 81?",
            quantityA: "Next number",
            quantityB: "243",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "What is the next number in the sequence 1, 2, 6, 12?",
            quantityA: "Next number",
            quantityB: "24",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 7,
            problem: "What is the next number in the sequence 4, 8, 16, 32?",
            quantityA: "Next number",
            quantityB: "64",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem: "What is the next number in the sequence 7, 14, 28, 56?",
            quantityA: "Next number",
            quantityB: "112",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 9,
            problem: "What is the next number in the sequence 2, 3, 5, 8?",
            quantityA: "Next number",
            quantityB: "13",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem: "What is the next number in the sequence 1, 5, 14, 30?",
            quantityA: "Next number",
            quantityB: "55",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 11,
            problem: "What is the next number in the sequence 8, 7, 5, 2?",
            quantityA: "Next number",
            quantityB: "-2",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem: "What is the next number in the sequence 10, 20, 30, 40?",
            quantityA: "Next number",
            quantityB: "50",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "13",
        title: "Puzzle Section 4",
        subtitle: "Complex Pattern Analysis",
        difficulty: "Hard",
        category: "puzzle",
        questions: [
          {
            id: 1,
            problem: "What is the next number in the sequence 1, 1, 2, 3, 5?",
            quantityA: "Next number",
            quantityB: "8",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem: "What is the next number in the sequence 2, 6, 12, 20?",
            quantityA: "Next number",
            quantityB: "30",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem: "What is the next number in the sequence 5, 15, 45, 135?",
            quantityA: "Next number",
            quantityB: "405",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "What is the next number in the sequence 1, 8, 27, 64?",
            quantityA: "Next number",
            quantityB: "125",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem: "What is the next number in the sequence 3, 4, 6, 9?",
            quantityA: "Next number",
            quantityB: "13",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 6,
            problem: "What is the next number in the sequence 4, 12, 36, 108?",
            quantityA: "Next number",
            quantityB: "324",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem: "What is the next number in the sequence 2, 4, 7, 11?",
            quantityA: "Next number",
            quantityB: "18",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 8,
            problem: "What is the next number in the sequence 10, 11, 13, 16?",
            quantityA: "Next number",
            quantityB: "20",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 9,
            problem: "What is the next number in the sequence 1, 3, 7, 15?",
            quantityA: "Next number",
            quantityB: "31",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem: "What is the next number in the sequence 6, 12, 24, 48?",
            quantityA: "Next number",
            quantityB: "96",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 11,
            problem: "What is the next number in the sequence 5, 6, 8, 11?",
            quantityA: "Next number",
            quantityB: "15",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem: "What is the next number in the sequence 2, 10, 50, 250?",
            quantityA: "Next number",
            quantityB: "1250",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
    ],
  },
  {
    category: "logic",
    sections: [
      {
        id: "7",
        title: "Logic Section 1",
        subtitle: "Logical Comparisons",
        difficulty: "Medium",
        category: "logic",
        questions: [
          {
            id: 1,
            problem:
              "If all humans are mortal and Socrates is a human, compare Socrates' mortality to a value.",
            quantityA: "Socrates is mortal",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem:
              "If all birds fly and penguins are birds, compare penguins fly to a value.",
            quantityA: "Penguins fly",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "14",
        title: "Logic Section 2",
        subtitle: "Advanced Logical Reasoning",
        difficulty: "Hard",
        category: "logic",
        questions: [
          {
            id: 1,
            problem:
              "If some cats are black and Fluffy is a cat, compare Fluffy is black to a value.",
            quantityA: "Fluffy is black",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 2,
            problem:
              "If all squares are rectangles, compare a square’s sides to a rectangle’s sides.",
            quantityA: "All sides equal",
            quantityB: "Opposite sides equal",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "Quantity A is greater",
          },
          {
            id: 3,
            problem: "If A implies B and B is false, compare A to a value.",
            quantityA: "A",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem:
              "If all primes are odd except 2, compare the number of even primes to a value.",
            quantityA: "Number of even primes",
            quantityB: "1",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem:
              "If x is an integer and x > 1, compare x being prime to x being composite.",
            quantityA: "x is prime",
            quantityB: "x is composite",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 6,
            problem:
              "If all roses are flowers, compare roses are plants to a value.",
            quantityA: "Roses are plants",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem: "If A or B is true and A is false, compare B to a value.",
            quantityA: "B",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem:
              "If all even numbers are divisible by 2, compare 4’s divisibility by 2 to a value.",
            quantityA: "4 is divisible by 2",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 9,
            problem:
              "If some dogs bark and Rover is a dog, compare Rover barks to a value.",
            quantityA: "Rover barks",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The relationship cannot be determined",
          },
          {
            id: 10,
            problem:
              "If all triangles have 3 sides, compare a triangle’s sides to a value.",
            quantityA: "Number of sides",
            quantityB: "3",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 11,
            problem: "If A and B are true, compare A or B to a value.",
            quantityA: "A or B",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem:
              "If no cats are dogs, compare a cat being a dog to a value.",
            quantityA: "A cat is a dog",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
      {
        id: "15",
        title: "Logic Section 3",
        subtitle: "Complex Logical Analysis",
        difficulty: "Research",
        category: "logic",
        questions: [
          {
            id: 1,
            problem: "If A implies B and A is true, compare B to a value.",
            quantityA: "B",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 2,
            problem:
              "If all integers are rational, compare 5 being rational to a value.",
            quantityA: "5 is rational",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 3,
            problem:
              "If some numbers are even, compare 3 being even to a value.",
            quantityA: "3 is even",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 4,
            problem: "If A is not B and B is true, compare A to a value.",
            quantityA: "A",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 5,
            problem:
              "If all circles are round, compare a circle’s shape to a value.",
            quantityA: "Circle is round",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 6,
            problem: "If x is even, compare x + 2 being even to a value.",
            quantityA: "x + 2 is even",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 7,
            problem:
              "If no birds are mammals, compare a sparrow being a mammal to a value.",
            quantityA: "Sparrow is a mammal",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 8,
            problem:
              "If A or B is false, compare A and B both being true to a value.",
            quantityA: "A and B are true",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 9,
            problem:
              "If all odd numbers are integers, compare 7 being an integer to a value.",
            quantityA: "7 is an integer",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 10,
            problem:
              "If some shapes are polygons, compare a circle being a polygon to a value.",
            quantityA: "Circle is a polygon",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 11,
            problem:
              "If A implies B and B implies C, compare A implying C to a value.",
            quantityA: "A implies C",
            quantityB: "True",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
          {
            id: 12,
            problem: "If x is positive, compare x being negative to a value.",
            quantityA: "x is negative",
            quantityB: "False",
            options: [
              "Quantity A is greater",
              "Quantity B is greater",
              "The two quantities are equal",
              "The relationship cannot be determined",
            ],
            answer: "The two quantities are equal",
          },
        ],
      },
    ],
  },
];
